<?xml version="1.0"?>
<package format="3">
  <name>cubic_navigation</name>
  <version>0.1.2</version>
  <description>CUBIC navigation package</description>

  <maintainer email="woojinchris15@gmail.com">RIVET</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
